# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/23a295e1-181f-4607-ab10-e2742feff4ce";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-56b95966-2788-4d74-bf8d-fbdfb4106322".device = "/dev/disk/by-uuid/56b95966-2788-4d74-bf8d-fbdfb4106322";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/CBC4-1849";
      fsType = "vfat";
    };

  fileSystems."/home/timlinux/gisdata" =
    { device = "/dev/disk/by-uuid/ec7da9cf-6a66-4ae3-a426-bde65b571e6e";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ef689831-6c83-442c-9a4e-49821cc24d07";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-ecea0325-79ab-4efc-adff-74de4982836f".device = "/dev/disk/by-uuid/ecea0325-79ab-4efc-adff-74de4982836f";

  fileSystems."/home/backups" =
    { device = "/dev/disk/by-uuid/a04d9c57-56ba-4e4d-a71e-36f1adf24fc4";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-b7dae669-00f7-4708-bf5a-858b0e70641e".device = "/dev/disk/by-uuid/b7dae669-00f7-4708-bf5a-858b0e70641e";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
